services:
  weather-pg:
    container_name: weather-pg
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weather_development

    ports:
      - 5432:5432
    restart: always

  weather-redis:
    container_name: weather-redis
    platform: linux/amd64
    image: redis
    volumes:
    - ./db/redis/data:/data
    ports:
      - 6379:6379
    restart: always

  weather-mailhog:
    container_name: weather-mailhog
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - "8025:8025" 
      - "1025:1025"  
    restart: always

  web:
    stdin_open: true
    tty: true
    platform: linux/amd64
    container_name: web
    build: .
    env_file:
      - .env
    environment:
      - RAILS_ENV=development
      - BUNDLE_WITHOUT=
      - DATABASE_URL=postgresql://postgres:password@weather-pg:5432/weather_development
    depends_on:
      - weather-pg
      - weather-redis
      - weather-mailhog
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    restart: always  
