volumes:
  pgadmin_data:
  bundle_cache: 

services:
  weather-pg:
    container_name: weather-pg
    platform: linux/amd64
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    ports:
      - ${PG_PORT}:5432
    restart: always

  weather-redis:
    container_name: weather-redis
    platform: linux/amd64
    image: redis
    volumes:
    - ./db/redis/data:/data
    ports:
      - ${REDIS_PORT}:6379
    restart: always

  mailhog:
    container_name: mailhog
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - "8025:8025"  # Interface web do MailHog
      - "1025:1025"  # SMTP server
    restart: always

  web:
    stdin_open: true
    tty: true
    platform: linux/amd64
    container_name: web
    build: .
    env_file:
      - .env
    depends_on:
      - weather-pg
      - weather-redis
      - mailhog
    command: ./bin/start
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - 3000
    restart: always  
